//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoSploit_TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoSploit_TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.AutoSploit_TextResource", typeof(AutoSploit_TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 asfconsole Automatically infiltrate the target using existing Exp 的本地化字符串。
        /// </summary>
        internal static string AsfConsole_Help {
            get {
                return ResourceManager.GetString("AsfConsole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似        d8888  .d8888b.  8888888888 .d8888b.  
        ///      d88888 d88P  Y88b 888       d88P  Y88b 
        ///     d88P888 Y88b.      888       888    888 
        ///    d88P 888  &quot;Y888b.   8888888   888        
        ///   d88P  888     &quot;Y88b. 888       888        
        ///  d88P   888       &quot;888 888       888    888 
        /// d8888888888 Y88b  d88P 888       Y88b  d88P 
        ///d88P     888  &quot;Y8888P&quot;  888        &quot;Y8888P&quot;  的本地化字符串。
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFConsole: Cannot access the &quot;AsfExp&quot; directory! 的本地化字符串。
        /// </summary>
        internal static string CannotAccessDirectory {
            get {
                return ResourceManager.GetString("CannotAccessDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFConsole: Cannot establish connection to the IP address! 的本地化字符串。
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create &quot;AsfExp&quot; Directory! 的本地化字符串。
        /// </summary>
        internal static string CreateDirFailed {
            get {
                return ResourceManager.GetString("CreateDirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name:	{0}
        ///System:	{1}
        ///Desc:	{2}
        ///Date:	{3}/{4}/{5}
        ///Rank:	{6} 的本地化字符串。
        /// </summary>
        internal static string DescriptionOutput {
            get {
                return ResourceManager.GetString("DescriptionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Please input the target IP, or input &quot;exit&quot; to close the application. 的本地化字符串。
        /// </summary>
        internal static string InputIP {
            get {
                return ResourceManager.GetString("InputIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Exps available!Put Exps into the &quot;AsfExp&quot; Directory! 的本地化字符串。
        /// </summary>
        internal static string NoExpsAvailable {
            get {
                return ResourceManager.GetString("NoExpsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFConsole: Access granted, password secured: {0}
        ///        Analysing current target`s network map... 的本地化字符串。
        /// </summary>
        internal static string SaveMap {
            get {
                return ResourceManager.GetString("SaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name:	System:	Rank:	 的本地化字符串。
        /// </summary>
        internal static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFConsole: Target is immune to this Exp! 的本地化字符串。
        /// </summary>
        internal static string TargetImmune {
            get {
                return ResourceManager.GetString("TargetImmune", resourceCulture);
            }
        }
    }
}
