//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EzHack_Dict {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EzHack_Dict() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.EzHack_Dict", typeof(EzHack_Dict).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 root
        ///654321
        ///123456
        ///TIGER
        ///DBSNMP
        ///root
        ///admin
        ///linkage123
        ///linkage124
        ///linkage125
        ///linkage001
        ///linkage010
        ///linkage@010
        ///precise_
        ///123qwe
        ///hanjian
        ///dasusr1
        ///db2fenc1
        ///db2inst2
        ///ibmpm200
        ///dasadm1
        ///ora
        ///teamsun
        ///venustech!@#
        ///test
        ///test123
        ///bocogo
        ///123
        ///123456
        ///xj@12531
        ///nagios
        ///root1234
        ///zxomm
        ///xj@12531
        ///adm
        ///eudemon
        ///password
        ///Admin@storage
        ///Admin@huawei.com
        ///huawei
        ///Change_me
        ///000001
        ///Changeme
        ///master
        ///CHina12530
        ///esaadmin
        ///pconsole
        ///nuucp
        ///mdmc
        ///mdccn
        ///mdmcn
        ///mdcc
        ///xjidc
        ///4aadmin
        ///123456
        ///jiankong
        ///inms [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Password_Dict {
            get {
                return ResourceManager.GetString("Password_Dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 root
        ///654321
        ///123456
        ///TIGER
        ///DBSNMP
        ///root
        ///admin
        ///linkage123
        ///linkage124
        ///linkage125
        ///linkage001
        ///linkage010
        ///linkage@010
        ///precise_
        ///123qwe
        ///xxzdgy
        ///dasusr1
        ///db2fenc1
        ///db2inst2
        ///ibmpm200
        ///dasadm1
        ///ora
        ///teamsun
        ///venustech!@#
        ///test
        ///test123
        ///bocogo
        ///123
        ///123456
        ///xj@12531
        ///nagios
        ///root1234
        ///zxomm
        ///xj@12531
        ///adm
        ///eudemon
        ///password
        ///Admin@storage
        ///Admin@huawei.com
        ///huawei
        ///Change_me
        ///000001
        ///Changeme
        ///master
        ///CHina12530
        ///esaadmin
        ///pconsole
        ///nuucp
        ///mdmc
        ///mdccn
        ///mdmcn
        ///mdcc
        ///xjidc
        ///4aadmin
        ///123456
        ///jiankong
        ///watas [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Password_Dict_Modified {
            get {
                return ResourceManager.GetString("Password_Dict_Modified", resourceCulture);
            }
        }
    }
}
