//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EzHack_TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EzHack_TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.EzHack_TextResource", typeof(EzHack_TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Brute: Failed to establish connection! 的本地化字符串。
        /// </summary>
        internal static string Brute_ConnectionFailed {
            get {
                return ResourceManager.GetString("Brute_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brute: Failed to brute-force the password! 的本地化字符串。
        /// </summary>
        internal static string Brute_Failed {
            get {
                return ResourceManager.GetString("Brute_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///      brute [ip addr] (optional: [option] [argument(s)]) Brute-force the designated host`s remote desktop password. Will create a proxy for intranet penetration.
        ///      Possible option(s):
        ///      -f [Document File] Use this file as the dictionary instead of the built-in one
        ///     的本地化字符串。
        /// </summary>
        internal static string Brute_Help {
            get {
                return ResourceManager.GetString("Brute_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password secured: {0}
        ///Analysing current target`s network map... 的本地化字符串。
        /// </summary>
        internal static string Brute_SaveMap {
            get {
                return ResourceManager.GetString("Brute_SaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 probe Scan the LAN that the remote host is connected to. 的本地化字符串。
        /// </summary>
        internal static string Probe_Help {
            get {
                return ResourceManager.GetString("Probe_Help", resourceCulture);
            }
        }
    }
}
