//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameController_TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameController_TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.GameController_TextResource", typeof(GameController_TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 PMAP: PCID enabled
        ///vm_page_bootstrap: 987323 free pages and 53061 wired pages
        ///kext submap [0xffffff7f8072e000 - 0xffffff8000000000], kernel text [0xffffff8000200000 - 0xffffff800072e000]
        ///zone leak detection enabled
        ///standard timeslicing quantum is 10000 us
        ///mig_table_max_displ = 72
        ///TSC Deadline Timer supported and enabled
        ///ACPICPU: ProcessorId=1 LocalApicId=0 Enabled
        ///ACPICPU: ProcessorId=2 LocalApicId=2 Enabled
        ///ACPICPU: ProcessorId=3 LocalApicId=1 Enabled
        ///ACPICPU: ProcessorId=4 LocalApicId=3 Enabled        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BootUp {
            get {
                return ResourceManager.GetString("BootUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档损坏！ 的本地化字符串。
        /// </summary>
        internal static string BrokenSave {
            get {
                return ResourceManager.GetString("BrokenSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已读取！ 的本地化字符串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要读取{0}的存档吗？ 的本地化字符串。
        /// </summary>
        internal static string Load_Option {
            get {
                return ResourceManager.GetString("Load_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档不存在！ 的本地化字符串。
        /// </summary>
        internal static string SaveNotExist {
            get {
                return ResourceManager.GetString("SaveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
