//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.GlobalConfig", typeof(GlobalConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:fail_save
        ///            address:127.0.0.1
        ///            info:HackTool OS Ver.0.03 Alpha
        ///        .
        /// </summary>
        internal static string Host0 {
            get {
                return ResourceManager.GetString("Host0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:hacktool_storage
        ///            address:119.131.233.33
        ///            password:HackingT0TheGate
        ///            waf:none
        ///            info:Door Server 2019 x64
        ///            exploit:i`m invincible
        ///        .
        /// </summary>
        internal static string Host1 {
            get {
                return ResourceManager.GetString("Host1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:tracer_at_home
        ///            address:119.131.100.86
        ///            password:Mar!onette_Never_S1eep
        ///            waf:weak
        ///            info:Door 10 Version 2004 x64
        ///            exploit:C# is the Best Language in the World
        ///        .
        /// </summary>
        internal static string Host2 {
            get {
                return ResourceManager.GetString("Host2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:media_storage
        ///            address:119.131.24.34
        ///            password:VirtualLiver
        ///            waf:tough
        ///            info:Door Server 2008 R2 x64
        ///            exploit:the storage of my delights and sorrows
        ///        .
        /// </summary>
        internal static string Host3 {
            get {
                return ResourceManager.GetString("Host3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:dummy1
        ///            address:119.131.124.50
        ///            password:password
        ///            waf:none
        ///            info:UBurst 16.04 x64
        ///            exploit:ola
        ///        .
        /// </summary>
        internal static string Host4 {
            get {
                return ResourceManager.GetString("Host4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:dummy2
        ///            address:119.131.124.51
        ///            password:webuser
        ///            waf:none
        ///            info:UBurst 18.04 x86
        ///            exploit:muda
        ///        .
        /// </summary>
        internal static string Host5 {
            get {
                return ResourceManager.GetString("Host5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            name:dummy3
        ///            address:119.131.124.52
        ///            password:noMoreVVeakP@ssw0rd!
        ///            waf:tough
        ///            info:Door XP SP3 x86
        ///            exploit:welcome
        ///        .
        /// </summary>
        internal static string Host6 {
            get {
                return ResourceManager.GetString("Host6", resourceCulture);
            }
        }
    }
}
