//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalConfig() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.GlobalConfig", typeof(GlobalConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:fail_save
        ///            address:127.0.0.1
        ///            info:HackTool OS Ver.0.03 Alpha
        ///         的本地化字符串。
        /// </summary>
        internal static string Host0 {
            get {
                return ResourceManager.GetString("Host0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:hacktool_storage
        ///            address:119.131.233.33
        ///            password:HackingT0TheGate
        ///            waf:none
        ///            info:Door Server 2019 x64
        ///            exploit:i`m invincible
        ///         的本地化字符串。
        /// </summary>
        internal static string Host1 {
            get {
                return ResourceManager.GetString("Host1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:tracer_at_home
        ///            address:119.131.100.86
        ///            password:Mar!onette_Never_S1eep
        ///            waf:weak
        ///            info:Door 10 Version 2004 x64
        ///            exploit:C# is the Best Language in the World
        ///         的本地化字符串。
        /// </summary>
        internal static string Host2 {
            get {
                return ResourceManager.GetString("Host2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:media_storage
        ///            address:119.131.24.34
        ///            password:VirtualLiver
        ///            waf:tough
        ///            info:Door Server 2008 R2 x64
        ///            exploit:the storage of my delights and sorrows
        ///         的本地化字符串。
        /// </summary>
        internal static string Host3 {
            get {
                return ResourceManager.GetString("Host3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:dummy1
        ///            address:119.131.124.50
        ///            password:123456
        ///            waf:none
        ///            info:UBurst 16.04 x64
        ///            exploit:ola
        ///         的本地化字符串。
        /// </summary>
        internal static string Host4 {
            get {
                return ResourceManager.GetString("Host4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:dummy2
        ///            address:119.131.124.51
        ///            password:webuser
        ///            waf:none
        ///            info:UBurst 18.04 x86
        ///            exploit:muda
        ///         的本地化字符串。
        /// </summary>
        internal static string Host5 {
            get {
                return ResourceManager.GetString("Host5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///            name:dummy3
        ///            address:119.131.124.52
        ///            password:noMoreVVeakP@ssw0rd!
        ///            waf:tough
        ///            info:Door XP SP3 x86
        ///            exploit:welcome
        ///         的本地化字符串。
        /// </summary>
        internal static string Host6 {
            get {
                return ResourceManager.GetString("Host6", resourceCulture);
            }
        }
    }
}
