//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mail_TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mail_TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.Mail_TextResource", typeof(Mail_TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 “↑”，“↓”移动光标，“Enter”执行操作 的本地化字符串。
        /// </summary>
        internal static string ClientHelp {
            get {
                return ResourceManager.GetString("ClientHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的收件箱空空如也=ω= 的本地化字符串。
        /// </summary>
        internal static string EmptyInbox {
            get {
                return ResourceManager.GetString("EmptyInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [离开] 的本地化字符串。
        /// </summary>
        internal static string ExitWriteMail {
            get {
                return ResourceManager.GetString("ExitWriteMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发件人： 的本地化字符串。
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你有{0}封未读邮件。 的本地化字符串。
        /// </summary>
        internal static string HaveUnread {
            get {
                return ResourceManager.GetString("HaveUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #来自 的本地化字符串。
        /// </summary>
        internal static string HeaderFrom {
            get {
                return ResourceManager.GetString("HeaderFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #时间 的本地化字符串。
        /// </summary>
        internal static string HeaderTime {
            get {
                return ResourceManager.GetString("HeaderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #标题 的本地化字符串。
        /// </summary>
        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mail 打开邮件客户端 的本地化字符串。
        /// </summary>
        internal static string Mail_Help {
            get {
                return ResourceManager.GetString("Mail_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  #邮件账户格式不规范！ 的本地化字符串。
        /// </summary>
        internal static string MailAddressUnmatched {
            get {
                return ResourceManager.GetString("MailAddressUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [另起一行] 的本地化字符串。
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已读 的本地化字符串。
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下任意按键回到收件箱 的本地化字符串。
        /// </summary>
        internal static string ReturnToInbox {
            get {
                return ResourceManager.GetString("ReturnToInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [发送] 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间： 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题： 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人： 的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未读 的本地化字符串。
        /// </summary>
        internal static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，欢迎回来！{1} 的本地化字符串。
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写邮件 的本地化字符串。
        /// </summary>
        internal static string WriteMail {
            get {
                return ResourceManager.GetString("WriteMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [“↑”，“↓”移动光标，“Enter”开始编辑，“Delete”清除当前行内容] 的本地化字符串。
        /// </summary>
        internal static string WriteMailHelp {
            get {
                return ResourceManager.GetString("WriteMailHelp", resourceCulture);
            }
        }
    }
}
