//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.PlotConfig", typeof(PlotConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blaze.
        /// </summary>
        internal static string blaze {
            get {
                return ResourceManager.GetString("blaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailbotservice_blaze.
        /// </summary>
        internal static string blaze_bot {
            get {
                return ResourceManager.GetString("blaze_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-reply-daily-world.
        /// </summary>
        internal static string daily_world {
            get {
                return ResourceManager.GetString("daily_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Cyberspace!.
        /// </summary>
        internal static string flag1 {
            get {
                return ResourceManager.GetString("flag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hack`em all from zero to one..
        /// </summary>
        internal static string flag2 {
            get {
                return ResourceManager.GetString("flag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you hear me? Hacker with three monitors..
        /// </summary>
        internal static string flag3 {
            get {
                return ResourceManager.GetString("flag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你收到了重要邮件！输入&quot;mail&quot;查看。.
        /// </summary>
        internal static string ImportantMail {
            get {
                return ResourceManager.GetString("ImportantMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心，有裤子被脱了.
        /// </summary>
        internal static string Lively_Mail01_Name {
            get {
                return ResourceManager.GetString("Lively_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近有个裤子被脱了。
        ///        我在库里似乎找到了些属于你的敏感信息，我把它们编辑到EZHack的默认字典里去了。
        ///        希望那堆信息里没有你的口令信息吧（笑）
        ///        我暂存到Hacktool_Storage那里去了。下载后记得删掉。.
        /// </summary>
        internal static string Lively_Mail01_Text {
            get {
                return ResourceManager.GetString("Lively_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没删掉吗？.
        /// </summary>
        internal static string Lively_Mail02_Name {
            get {
                return ResourceManager.GetString("Lively_Mail02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你是不是丝毫对密码泄露不上心啊？
        ///            如果是这样，我就拿这个字典把所有网站都炸一遍，
        ///            然后简介全部写上&quot;Tracer你好菜啊&quot;如何？
        ///            
        ///            话说，你已经好几天没和我，还有Wardog的其他人发邮件了。你最近很忙吗？.
        /// </summary>
        internal static string Lively_Mail02_Text {
            get {
                return ResourceManager.GetString("Lively_Mail02_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AD&gt;这周的国内大事记(1/2).
        /// </summary>
        internal static string Lively_Mail03_Name {
            get {
                return ResourceManager.GetString("Lively_Mail03_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本周的国内大事记：
        ///            1. 新星游戏制作人离奇失踪？
        ///            · 独立游戏制作人Tracer据报已音信全无长达72小时。其家属已经报警。
        ///            · Tracer的新作《战区连结 Re://Deploy》预定于8月1日直播公布，但从7月29日开始其朋友及家属就联络不到他。
        ///            · 与Tracer合作的大型游戏厂商，静观暴雨的发言人称并不知情，“我们也想找到他”。
        ///            · 据了解，Tracer的上部视觉小说游戏《永不落幕的舞台剧》以出众的剧情表现手法被业界誉为“独立游戏的破壁者”。
        ///            
        ///            2. 脑机技术新突破，数字世界遨游指日可望？
        ///            · 科学家RoFox宣布找到新方法将人类大脑与计算机进行神经连接。
        ///            · 该技术将可以让人类的意识直接与计算机交互，而无需使用眼睛手脚、键盘鼠标进行交互。
        ///            · 虚拟现实（VR）游戏运营团队VirtuaReal发出公开信感谢她为人类所作的贡献，“有朝一日现实世 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lively_Mail03_Text {
            get {
                return ResourceManager.GetString("Lively_Mail03_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AD&gt;这周的国内大事记(2/2).
        /// </summary>
        internal static string Lively_Mail04_Name {
            get {
                return ResourceManager.GetString("Lively_Mail04_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到该邮件存在垃圾链接。
        ///        邮件过滤器已屏蔽该邮件。.
        /// </summary>
        internal static string Lively_Mail04_Text {
            get {
                return ResourceManager.GetString("Lively_Mail04_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiction.mail.
        /// </summary>
        internal static string Mail_Address {
            get {
                return ResourceManager.GetString("Mail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  __      __      ____      __________   ___
        ///|\  \   /\ \    /\   \     \         \ |\  \
        ///| ## \ /  ##   /  ####\    \########## | ###
        ///| ####\\####  /  ## \##\      | ##     | ###
        ///| ##\#### ## |\ ########\  ___| ##___  | ###______
        ///| ## \##| ## | ###   \###  \   \##   \ | ###      \
        /// \##     \##  \##     \##  \##########  \##########.
        /// </summary>
        internal static string Mail_ASCII {
            get {
                return ResourceManager.GetString("Mail_ASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Contact.
        /// </summary>
        internal static string Main01_Mail01_Name {
            get {
                return ResourceManager.GetString("Main01_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到该邮件的人，请按照下面指示操作：
        ///            1. 入侵1号网络靶机。
        ///            它的防御相当简陋，因为它的密码简单到世界知名。
        ///            先安装远程连接程序。安装包在系统根目录下。
        ///            然后连接[dummy1_address]，猜测密码，然后查看里面的flag文件内容。
        ///            2. 将靶机的flag的内容用邮件发给该邮件发件人的地址。
        ///            利用&quot;help&quot;了解系统操作。
        ///            如果不会，就发封邮件过来。.
        /// </summary>
        internal static string Main01_Mail01_Text {
            get {
                return ResourceManager.GetString("Main01_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有人吗？.
        /// </summary>
        internal static string Main01_Mail02_Name {
            get {
                return ResourceManager.GetString("Main01_Mail02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ······已经失踪2周了，没有人找得到这个系统吗？.
        /// </summary>
        internal static string Main01_Mail02_Text {
            get {
                return ResourceManager.GetString("Main01_Mail02_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Contact：补充.
        /// </summary>
        internal static string Main01_Sub01_Mail01_Name {
            get {
                return ResourceManager.GetString("Main01_Sub01_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            时间有点紧，我先长话短说了。
        ///            install(空格）+ 文件名是安装程序。
        ///            connect(空格）+ ip地址是连接指定主机。
        ///            前提是那台主机是可达的，也就是你的系统可以连接到那台主机。
        ///            然后，为了方便一般人也能快速熟悉系统，Hacktool的操作与Linux系统类似，有一些指令是通用的。
        ///            你想问密码？我都说了，弱到世界知名了！搜索一下，然后一个一个试，绝对没有错。
        ///            最后，多用&quot;help&quot;！多用&quot;help&quot;！多用&quot;help&quot;！.
        /// </summary>
        internal static string Main01_Sub01_Mail01_Text {
            get {
                return ResourceManager.GetString("Main01_Sub01_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学习使用工具.
        /// </summary>
        internal static string Main02_Mail01_Name {
            get {
                return ResourceManager.GetString("Main02_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice！
        ///            看样子您还挺会用这系统的！也许您有当黑客的潜力呢？
        ///            我是Blaze，我的朋友是Tracer，你在用的这套系统就是他开发的。
        ///            他似乎因为遇到了一些危险，于是启动了曾经写的程序的后门，向外界寻求帮助。
        ///            现在，你已经证明了自己，可以去我们的黑客素材库做客了！
        ///            地址是[hacktool_storage_address]，密码是[hacktool_storage_password]。
        ///            去那里把EZHack下载下来，然后试试用EZHack的功能攻击2号网络靶机。
        ///            2号网络靶机的地址不太记得了，
        ///            不过2号靶机与1号靶机相连。
        ///            还是一样：如果不太会，就发封邮件给我。
        ///            一旦解出这个谜题，就将flag的内容用邮件发给我。.
        /// </summary>
        internal static string Main02_Mail01_Text {
            get {
                return ResourceManager.GetString("Main02_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学习使用工具：补充.
        /// </summary>
        internal static string Main02_Sub01_Mail01_Name {
            get {
                return ResourceManager.GetString("Main02_Sub01_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不会吧？我想收回那句“有潜力”了······
        ///            EZHack的作用有2个：
        ///            brute：使用内置的字典，或是指定另一个字典进行远程连接爆破攻击。
        ///            probe：连接到别的主机时使用，扫描当前主机连接到的其他主机，并获得其信息。
        ///            另外，Hacktool的远程连接被改造过，现在它会记得之前连接过的主机信息，
        ///            下次想深入连接更深入的内网时，直接输入目标地址就行了，中途这个工具会自动建立代理。.
        /// </summary>
        internal static string Main02_Sub01_Mail01_Text {
            get {
                return ResourceManager.GetString("Main02_Sub01_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 太棒了！.
        /// </summary>
        internal static string Prologue_Ending_Mail01_Name {
            get {
                return ResourceManager.GetString("Prologue_Ending_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 太棒了！你逐渐理解一切！
        ///            我也没什么东西要教你了，因为你（也许）已经掌握如何在这个未知世界里摸索。
        ///            再去一次Hacktool_Storage吧。我给临行的您准备了点新礼物。它可以保护你。
        ///            说来讽刺，在寻找Tracer的路上的阻碍之一居然是Tracer遗留下的造物······
        ///            先去Tracer的家用电脑收集情报吧。平时靶机和素材库都是由他帮忙运营，因此他的电脑应该是连接着的。
        ///            密码如果不出意外的话······他应该藏在你的系统。.
        /// </summary>
        internal static string Prologue_Ending_Mail01_Text {
            get {
                return ResourceManager.GetString("Prologue_Ending_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的邮件，我已经收到了.
        /// </summary>
        internal static string Side01_Ending_Mail01_Name {
            get {
                return ResourceManager.GetString("Side01_Ending_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 哔啵~
        ///        我是Blaze的邮箱机器人服务，该服务由noctchill™研发。
        ///        以下是主人的留言：
        ///        “发了发了，我B哥啥时候骗过你啊（滑稽）。”.
        /// </summary>
        internal static string Side01_Ending_Mail01_Text {
            get {
                return ResourceManager.GetString("Side01_Ending_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新漏洞新发现.
        /// </summary>
        internal static string Side01_Mail01_Name {
            get {
                return ResourceManager.GetString("Side01_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你给我的那个AutoSploit可扩展性是真滴强。
        ///        我最近才找到一个UBurst的0日漏洞，然后用你的工具为平台弄了一个自动脚本。
        ///        收到这封邮件后就给我的机器人[BlazeBotMail]发一封邮件吧。
        ///        然后机器人会自动把Exp上传到Hacktool_Storage那里。.
        /// </summary>
        internal static string Side01_Mail01_Text {
            get {
                return ResourceManager.GetString("Side01_Mail01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??????.
        /// </summary>
        internal static string Side02_Ending_Mail01_Name {
            get {
                return ResourceManager.GetString("Side02_Ending_Mail01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你去打了哪个靶机？.
        /// </summary>
        internal static string Side02_Ending_Mail01_Text {
            get {
                return ResourceManager.GetString("Side02_Ending_Mail01_Text", resourceCulture);
            }
        }
    }
}
