//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shell_TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shell_TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.Shell_TextResource", typeof(Shell_TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 cat [目录/文件] 将目标文件以文本文件形式输出 的本地化字符串。
        /// </summary>
        internal static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cd [目录] 前往该目录 的本地化字符串。
        /// </summary>
        internal static string cd {
            get {
                return ResourceManager.GetString("cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cp [旧目录/文件] [新目录/文件] 复制文件或目录 的本地化字符串。
        /// </summary>
        internal static string cp {
            get {
                return ResourceManager.GetString("cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件（夹）不存在！ 的本地化字符串。
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 help 打开帮助 的本地化字符串。
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    ___                  ____  ____
        ///  / _ \___  ___  ____  / __ \/ __/
        /// / // / _ \/ _ \/ __/ / /_/ /\ \  
        ////____/\___/\___/_/    \____/___/ 的本地化字符串。
        /// </summary>
        internal static string Help_Door {
            get {
                return ResourceManager.GetString("Help_Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ___  ___  ________  ________  ___  __            _________  ________  ________  ___
        ///|\  \|\  \|\   __  \|\   ____\|\  \|\  \         |\___   ___\\   __  \|\   __  \|\  \
        ///\ \  \\\  \ \  \|\  \ \  \___|\ \  \/  /|_       \|___ \  \_\ \  \|\  \ \  \|\  \ \  \
        /// \ \   __  \ \   __  \ \  \    \ \   ___  \           \ \  \ \ \  \\\  \ \  \\\  \ \  \
        ///  \ \  \ \  \ \  \ \  \ \  \____\ \  \\ \  \           \ \  \ \ \  \\\  \ \  \\\  \ \  \_____
        ///   \ \__\ \__\ \__\ \__\ \_______\ \__\\ \__\           \ \__\ \ \_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help_HackTool {
            get {
                return ResourceManager.GetString("Help_HackTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |\     /|(  ___ \ |\     /|(  ____ )(  ____ \\__   __/
        ///| )   ( || (   ) )| )   ( || (    )|| (    \/   ) (   
        ///| |   | || (__/ / | |   | || (____)|| (_____    | |   
        ///| |   | ||  __ (  | |   | ||     __)(_____  )   | |   
        ///| |   | || (  \ \ | |   | || (\ (         ) |   | |   
        ///| (___) || )___) )| (___) || ) \ \__/\____) |   | |   
        ///(_______)|/ \___/ (_______)|/   \__/\_______)   )_( 的本地化字符串。
        /// </summary>
        internal static string Help_UBurst {
            get {
                return ResourceManager.GetString("Help_UBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 install [可执行文件] 安装新程序 的本地化字符串。
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装成功！输入“help”查看新命令。 的本地化字符串。
        /// </summary>
        internal static string InstallAction_Finish {
            get {
                return ResourceManager.GetString("InstallAction_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装！ 的本地化字符串。
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 load 恢复系统快照(PS：可能会伴随着小规模的时空回溯) 的本地化字符串。
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ls (可选)[目录] 列出本目录下所有文件和目录 的本地化字符串。
        /// </summary>
        internal static string ls {
            get {
                return ResourceManager.GetString("ls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式错误！ 的本地化字符串。
        /// </summary>
        internal static string MismatchedFormat {
            get {
                return ResourceManager.GetString("MismatchedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mkdir [目录] 创建新目录 的本地化字符串。
        /// </summary>
        internal static string mkdir {
            get {
                return ResourceManager.GetString("mkdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mv [旧目录/文件] [新目录/文件] 移动文件或目录 的本地化字符串。
        /// </summary>
        internal static string mv {
            get {
                return ResourceManager.GetString("mv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在同名文件（夹）！ 的本地化字符串。
        /// </summary>
        internal static string NameConflict {
            get {
                return ResourceManager.GetString("NameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少HackTool.dll! 的本地化字符串。
        /// </summary>
        internal static string RequireDLL {
            get {
                return ResourceManager.GetString("RequireDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rm [目录/文件] 删除文件或目录 的本地化字符串。
        /// </summary>
        internal static string rm {
            get {
                return ResourceManager.GetString("rm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save 保存当前系统快照 的本地化字符串。
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving current process... 的本地化字符串。
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知参数！请输入“help”查阅帮助信息 的本地化字符串。
        /// </summary>
        internal static string UnknownArgument {
            get {
                return ResourceManager.GetString("UnknownArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知指令！请输入“help”查阅帮助信息 的本地化字符串。
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
