//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarzoneConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WAF_TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WAF_TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarzoneConnect.Properties.WAF_TextResource", typeof(WAF_TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///      _________
        ///      |\       /|
        ///      | \     / |
        ///      |         |
        ///      | NO DATA |
        ///      |         |
        ///      | /     \ |
        ///      |/_______\|
        ///     的本地化字符串。
        /// </summary>
        internal static string AcStyle_Nodata {
            get {
                return ResourceManager.GetString("AcStyle_Nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audition Start! 的本地化字符串。
        /// </summary>
        internal static string Audition_Start {
            get {
                return ResourceManager.GetString("Audition_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad... - 代码对抗系统出现错误，正在清除失效代码······ 的本地化字符串。
        /// </summary>
        internal static string Bad_Result {
            get {
                return ResourceManager.GetString("Bad_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A problem has been detected and HackTool has been shut down to prevent damage
        ///to your computer.
        ///			
        ///If this is the first time you&apos;ve seen this stop error screen,
        ///restart your computer. If this screen appears again, follow
        ///these steps: 
        ///			
        ///Check to be sure you have adequate disk space. If a driver is
        ///identified in the stop message, disable the driver or check
        ///with the manufacturer for driver updates. Try changing video
        ///adapters.
        ///
        ///Check with your hardware vendor for any BIOS updates. Disable
        ///BIO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Bsod_Text {
            get {
                return ResourceManager.GetString("Bsod_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +-----------+
        ///|           |
        ///+-----------+ 的本地化字符串。
        /// </summary>
        internal static string Enter_Frame {
            get {
                return ResourceManager.GetString("Enter_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Good~ - 后台编译已完成，启动自动按键防御系统 的本地化字符串。
        /// </summary>
        internal static string Good_Result {
            get {
                return ResourceManager.GetString("Good_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 from ajpy.ajp import AjpResponse, AjpForwardRequest, AjpBodyRequest, NotFoundException
        ///from pprint import pprint, pformat
        ///
        ///from base64 import b64encode
        ///import socket
        ///import argparse
        ///import logging
        ///import re
        ///import os
        ///import logging
        ///import sys
        ///try:
        ///	from urllib import unquote
        ///except ImportError:
        ///	from urllib.parse import unquote
        ///
        ///def setup_logger():
        ///	logger = logging.getLogger(&apos;meow&apos;)
        ///	handler = logging.StreamHandler()
        ///	logger.addHandler(handler)
        ///	logger.setLevel(logging.DEBUG)
        ///
        ///	return [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HackCode_AJPy {
            get {
                return ResourceManager.GetString("HackCode_AJPy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 inswafc 将WAFirecracker安装入系统内核中 的本地化字符串。
        /// </summary>
        internal static string Inswafc_Help {
            get {
                return ResourceManager.GetString("Inswafc_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal - 请继续对抗WAF 的本地化字符串。
        /// </summary>
        internal static string Normal_Result {
            get {
                return ResourceManager.GetString("Normal_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perfect!! - 数据溯源分析完成，WAF的0Day漏洞已取得 的本地化字符串。
        /// </summary>
        internal static string Perfect_Result {
            get {
                return ResourceManager.GetString("Perfect_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;&lt; It`s time &gt;&gt; 的本地化字符串。
        /// </summary>
        internal static string Pixy_Its_Time {
            get {
                return ResourceManager.GetString("Pixy_Its_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按回车键以继续 的本地化字符串。
        /// </summary>
        internal static string Press_Enter {
            get {
                return ResourceManager.GetString("Press_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看准时机，按下空格！ 的本地化字符串。
        /// </summary>
        internal static string Press_Space {
            get {
                return ResourceManager.GetString("Press_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下空格以继续 的本地化字符串。
        /// </summary>
        internal static string Press_Space_To_Continue {
            get {
                return ResourceManager.GetString("Press_Space_To_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unauthorized Connection Detected 的本地化字符串。
        /// </summary>
        internal static string Unauthorized_Connection {
            get {
                return ResourceManager.GetString("Unauthorized_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于
        ///			WAFirecracker 的本地化字符串。
        /// </summary>
        internal static string Wafc_About {
            get {
                return ResourceManager.GetString("Wafc_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正义(?)的Hero，WAFirecracker参上！
        ///			本系统内置插件可协助使用者应对网络追踪、数据溯源以及反制侵略型防火墙。
        ///			给Tracer: 有兴趣把这插件内置到HackTool吗？ 的本地化字符串。
        /// </summary>
        internal static string Wafc_About_Text {
            get {
                return ResourceManager.GetString("Wafc_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在使用0Day漏洞绕过... 的本地化字符串。
        /// </summary>
        internal static string Wafc_Bypass {
            get {
                return ResourceManager.GetString("Wafc_Bypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 当前防御能力等级为： {1} 的本地化字符串。
        /// </summary>
        internal static string Wafc_DefenceLevel {
            get {
                return ResourceManager.GetString("Wafc_DefenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离开帮助文档 的本地化字符串。
        /// </summary>
        internal static string Wafc_Exit {
            get {
                return ResourceManager.GetString("Wafc_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我想我还没
        ///			准备好 的本地化字符串。
        /// </summary>
        internal static string Wafc_Exit_No {
            get {
                return ResourceManager.GetString("Wafc_Exit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前方是洪水滔天的恶意代码，你现在的准备没问题吗？ 的本地化字符串。
        /// </summary>
        internal static string Wafc_Exit_Text {
            get {
                return ResourceManager.GetString("Wafc_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大丈夫萌大奶 的本地化字符串。
        /// </summary>
        internal static string Wafc_Exit_Yes {
            get {
                return ResourceManager.GetString("Wafc_Exit_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 已获得WAF的0Day漏洞 的本地化字符串。
        /// </summary>
        internal static string Wafc_ExpAcquired {
            get {
                return ResourceManager.GetString("Wafc_ExpAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *** secureprotocol.sys - Failed to handle service fatal error. 的本地化字符串。
        /// </summary>
        internal static string Wafc_Failed {
            get {
                return ResourceManager.GetString("Wafc_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wafc_flow_analyser.sys 的本地化字符串。
        /// </summary>
        internal static string Wafc_Flow_Analyser_Sys {
            get {
                return ResourceManager.GetString("Wafc_Flow_Analyser_Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用WAFirecracker！
        ///			当前版本为0.28.3 alpha
        ///			按下对应按键阅读帮助文档 的本地化字符串。
        /// </summary>
        internal static string Wafc_HelpText {
            get {
                return ResourceManager.GetString("Wafc_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WAFC帮助说明 的本地化字符串。
        /// </summary>
        internal static string Wafc_HelpTitle {
            get {
                return ResourceManager.GetString("Wafc_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 安装成功！ 的本地化字符串。
        /// </summary>
        internal static string Wafc_Installed {
            get {
                return ResourceManager.GetString("Wafc_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wafc_main.sys 的本地化字符串。
        /// </summary>
        internal static string Wafc_Main_Sys {
            get {
                return ResourceManager.GetString("Wafc_Main_Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用说明 的本地化字符串。
        /// </summary>
        internal static string Wafc_Manual {
            get {
                return ResourceManager.GetString("Wafc_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是跨时代的信息安全工具，所以
        ///			唯一操作就是用最快速度敲打键盘！
        ///			注意在结束阶段需要过一次QTE。 的本地化字符串。
        /// </summary>
        internal static string Wafc_Manual_Text {
            get {
                return ResourceManager.GetString("Wafc_Manual_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wafc_package_sender.sys 的本地化字符串。
        /// </summary>
        internal static string Wafc_Package_Sender_Sys {
            get {
                return ResourceManager.GetString("Wafc_Package_Sender_Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wafc_pseudo_gui.sys 的本地化字符串。
        /// </summary>
        internal static string Wafc_Pseudo_Gui_Sys {
            get {
                return ResourceManager.GetString("Wafc_Pseudo_Gui_Sys", resourceCulture);
            }
        }
    }
}
